In [40]:
import numpy as np

In [330]:
np_ar=np.array(ar2)

In [331]:
np_ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [332]:
new_ar=np.append(np_ar,[56,67,78])

In [333]:
new_ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 56, 67, 78])

In [42]:
ar1 = np.arange(13)

In [43]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [334]:
#delete ele from array
np_ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [336]:
nr=np.delete(np_ar,np.where(np_ar==2.0))

In [337]:
nr

array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [338]:
l1 =[1,45,23,90,78,12,94,26,15,8,7]

In [340]:
new_ar[new_ar<30]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [341]:
# print the value <20 and value >50
#for and operation using &
#for or operation use
(new_ar<20) &(new_ar>50)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [342]:
new_ar[new_ar<30]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [13]:
np.identity(5, dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [51]:
reshaped_array = ar1.reshape(13,1)

In [50]:
ar1
len(ar1)

13

In [16]:
import array as arr

In [49]:
ar1
len(ar1)

13

In [46]:
reshaped_array = ar1.reshape(13,1)

In [47]:
reshaped_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [44]:
ar2=np.arange(25)


In [45]:
ar2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ar2 = np.arange(25).reshape(5,5)


In [25]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ar2.shape

(5, 5)

In [34]:
#ar2[rows:columns,step]
#ar2 = np.arrange(25).reshape(5,5)# ar2[rows,columns,step]
#ar2[row_start:row_end, col_start,col_end,step]
ar2[0:3 , 1:4]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [35]:
ar2[0:2 ,]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
ar2[1:4]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [29]:
ar2[1:3]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
ar2[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
ar2[0:1]

array([[0, 1, 2, 3, 4]])

In [38]:
ar2[-1:2]

array([], shape=(0, 5), dtype=int32)

In [52]:
ar2[1:5]

array([1, 2, 3, 4])

In [53]:
ar2[-3:-5]

array([], dtype=int32)

In [54]:
ar2[-4:-2]

array([21, 22])

In [74]:
ar2[-4:-2 -4:-2]

array([21])

In [61]:
#tasks
#1.to print 27, 28, 37, 38 ---> 2.)
#2.to print 34, 25, 44, 45
#3.print 18,19
#4.print 31,31,40,41
ar3 = np.arange(50).reshape(5,10)

In [62]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [72]:
#linespace()
np.sum(ar3)

1225

In [65]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
#to add based on column wise axis=0
np.sum(ar3, axis=0)
#to add based on column wise axis=1
np.sum(ar3, axis=1)


array([ 45, 145, 245, 345, 445])

In [67]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [69]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
#mean -->average
#median -->center value
#mode -->repeated value
#variance -->median/total no of elements
#std -->square root of variance


In [92]:
#linspace()
#it is used to print the evenly seperated printed 
# between 2 range of values
np.linspace(1,10, 4 ,dtype=int) #--> linespace(start,end,num of values)

array([ 1,  4,  7, 10])

In [80]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [90]:
np.linspace(12,30, 12, retstep=True)

(array([12.        , 13.63636364, 15.27272727, 16.90909091, 18.54545455,
        20.18181818, 21.81818182, 23.45454545, 25.09090909, 26.72727273,
        28.36363636, 30.        ]),
 1.6363636363636365)

In [96]:
#random module
#np.random.randint(start,end)
#np.randomrandint(40)
#or
# to generate random numbers between the range
np.random.randint(20,30)

26

In [99]:
np.random.randint(20,30,3)

array([23, 23, 26])

In [104]:
#rand() -->
#to get the randomly generated values from 0 t 1, based 0n
#uniform distribution
np.random.rand(20)

array([0.08880022, 0.35664009, 0.59433226, 0.27386713, 0.19868214,
       0.28429456, 0.70790612, 0.74256058, 0.18921963, 0.75853456,
       0.70491736, 0.99145313, 0.92082322, 0.38708177, 0.75995781,
       0.5927986 , 0.71029756, 0.84783921, 0.72883922, 0.48059791])

In [105]:
np.random.rand(3,3)


array([[0.07129156, 0.50145881, 0.83788239],
       [0.00393269, 0.9915516 , 0.38448023],
       [0.98506669, 0.26448502, 0.26034265]])

In [106]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [108]:
#rand() -->
#to get the randomly generated values from 0 t 1, based 0n
#uniform distribution

np.random.randn(5)

array([ 0.70781192,  0.5599688 , -0.71269177, -1.55461886,  0.82494002])

In [109]:
#rand() -->
#to get the randomly generated values from 0 t 1, based 0n
#uniform distribution
np.random.randn(5,4)

array([[-0.38657835,  0.77943489,  1.09582617,  1.45777129],
       [-0.98553125, -1.28565201, -0.68791493,  0.27326281],
       [ 0.8458601 , -1.65885264,  1.08343386,  0.20973206],
       [ 0.31060301,  1.29525   , -0.83062274,  0.5028387 ],
       [ 0.75824716, -2.09581389, -0.14567835,  1.9251809 ]])

In [110]:
ar3.min()

0

In [111]:
ar3.max()

49

In [114]:
# to find the index  of min values
l1= [56,89,90,67,45]
print(l1.index(67))


3


In [113]:
print(ar3.tolist())

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29], [30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]


In [119]:
l1= [56,89,90,67,45]
np1 = np.array(l1)
print(np1.argmin())     #argmin() --> to find the min values index position in an array

print(np1.argmax())     #argmin() --> to find the max values index position in an array

print(np1.argmax())
print(np1.argmin())

4
2
2
4


In [126]:
np.sin(np1)
np.cos(np1)
np.tan(np1)
1/np.tan(np1)
1/np.sin(np1)

array([-1.91735803,  1.16269686,  1.11857241, -1.16887977,  1.17522136])

In [127]:
np.cos(np1)/np.sin(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [143]:
np2 = np.array([1,2,3,6])
np3 = np.array([4,5,6,4])

#(1*4)+(2*5)+(3*6)+(6*4)
#np2*np3

56

In [144]:
np2 = np.array([1,2,3,6])
np3 = np.array([4,5,6,4])
result = np.sum(np2 * np3)

print(result)

56


In [157]:
np2 = np.array([1,2,3,6])
np3 = np.array([4,5,6,4])


#(1*4)+(2*5)+(3*6)+(6*4)
#np2*np3
fname = np.array(["geetha", "hari", "hafee" ,"yashu"])
pname= np.array(["p1", "p2", "p3" ,"p4"])
#fname.tostring

In [156]:
fname

array(['geetha', 'hari', 'hafee', 'yashu'], dtype='<U6')

In [150]:
pname

array(['p1', 'p2', 'p3', 'p4'], dtype='<U2')

In [190]:
#task1: write python code to add below 2 arrays
np2 = np.array([1,2,3,6])
np3 = np.array([4,5,6,4])

len1 = len(np2)
len2 = len(np3)

diff = abs(len1-len2)
for val in range(diff):
 np3 = np.append(np3, 1)
    
np.sum((np2*np3))

#(1*4)+(2*5)+(3*6)+(6*4)
#np2*np

56

In [187]:
np1 = np.array([1.34,56,78,np.nan,np.nan])


In [188]:
np1

array([ 1.34, 56.  , 78.  ,   nan,   nan])

In [189]:
np.isnan(np1)

array([False, False, False,  True,  True])

In [173]:
#to print nan values
np1[np.isnan(np1)]

array([nan, nan])

In [182]:
#to eliminate nan values
np1[~np.isnan(np1)]

array([ 1.34, 56.  , 78.  ])

In [184]:
np2 = np.array([1,2,3])
np3 = np.array([4,5,6])

np.dot(np2,np3)

32

In [192]:
# pandas
import pandas as pd
# pandas is defines as an open-source library that provides 
#high performance ndata manipulation in python
#data analysis requries lot of processing such as restructing,cleaning,mergin,manipulating etc-- we prefer panda to perform 
# above functionsalities coz it is fast ,simple than other tools.

#pandas is built on numpy,numpy is requried for  operating
#pandas


In [194]:
#------>pandas series : 
#labelled series is a data structure with one 
#dimensional labelled array
#it is a primary building block of dataframe,making it's

#rows and columns

arr

<module 'array' (built-in)>

In [195]:
labels = ['a', 'b', 'c']
my_data = [10,20,30]
arr =np.array(my_data)
d = {"a" :100, "b": 200, "c" :300}

In [196]:
arr


array([10, 20, 30])

In [198]:
#syntax --> panda.series(data=none,index=none,dtype=none,name=none,copy= trueor false)
#eg:1
import pandas as pd

In [203]:
#series withn labels
#pd.series(data=my_data, index=labels)
#or
pd.Series(my_data, index=labels)

a    10
b    20
c    30
dtype: int64

In [202]:
type(pd.Series(my_data))

pandas.core.series.Series

In [205]:
pd.Series(data=[print,len, sum])

0    <built-in function print>
1      <built-in function len>
2      <built-in function sum>
dtype: object

In [214]:
class profile:
    @property
    def display(self):
        print("my name is Geetha")
              
p=profile()
p.display

my name is Geetha


In [222]:
def decor(func):
    def inner():
        str1 = func()
        return str1.upper()
    return inner
@decor
def greet():
    return "good morning"
print(greet())


GOOD MORNING


In [235]:
Ser2=pd.Series([1,2,3,4,5], ['USA',"INDIA","CANADA","uk","egypt"])

In [237]:
Ser2

USA       1
INDIA     2
CANADA    3
uk        4
egypt     5
dtype: int64

In [254]:
#access value using indexing
Ser2[0:3]

USA       1
INDIA     2
CANADA    3
dtype: object

In [253]:
Ser2['china'] = "duplicte"

In [362]:
Ser2

USA              1
INDIA            2
CANADA           3
uk               4
egypt            5
china     duplicte
dtype: object

In [360]:
#to create a newdata in series
Ser2

USA              1
INDIA            2
CANADA           3
uk               4
egypt            5
china     duplicte
dtype: object

In [258]:
Ser2.drop('USA')

INDIA            2
CANADA           3
uk               4
egypt            5
china     duplicte
dtype: object

In [301]:
S1=pd.Series([1,2,3],['USA','INDIA','canada'])
S1+S2

NameError: name 'S2' is not defined

In [268]:
# Data frames
#pd.dataframe(datas,row_label,col_label)


In [273]:
df = pd.DataFrame(np.random.randn(5,4))
df

0         1         2         3
0  0.388516 -1.005353  2.143068 -1.254009
1 -0.641478  0.480527 -1.525119  0.278461
2  0.686141 -1.172872  0.610010 -0.064440
3 -0.971236  0.843966 -0.094427 -0.895815
4 -1.959857 -0.825737  0.457047  1.248509

In [293]:
df = pd.DataFrame(data=d)
df

col1  col2  col3
0     1     3     5
1     2     4     6

In [290]:
#to convert dictionary to dataframes
d = {"col1":[1,2],"col2":[3,4],"col3":[5,6]}

In [291]:
d

{'col1': [1, 2], 'col2': [3, 4], 'col3': [5, 6]}

In [282]:
df

0         1         2         3
0  0.388516 -1.005353  2.143068 -1.254009
1 -0.641478  0.480527 -1.525119  0.278461
2  0.686141 -1.172872  0.610010 -0.064440
3 -0.971236  0.843966 -0.094427 -0.895815
4 -1.959857 -0.825737  0.457047  1.248509

In [285]:
df =pd.DataFrame(d, ["row1","row2"])

In [286]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [287]:
df.index


Index(['row1', 'row2'], dtype='object')

In [288]:
df

col1  col2  col3
row1     1     3     5
row2     2     4     6

In [346]:
df=pd.DataFrame(np.random.randn(5,4), ['A', 'B' ,'C', 'D', 'E'],['w','x','y','z'])

In [347]:
df

w         x         y         z
A -0.082347 -0.751475  0.623973 -0.185253
B  0.436654  0.179722  0.193585  2.167517
C -0.006839 -1.989425  0.534744 -0.840111
D -0.859714  1.503477  1.560717 -0.320598
E  0.743590  1.038990 -0.523050 -1.369887

In [298]:
df.index #--->get all the row name

RangeIndex(start=0, stop=2, step=1)

In [299]:
  df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [300]:
type(df)

pandas.core.frame.DataFrame

In [303]:
df.dtypes

col1    int64
col2    int64
col3    int64
dtype: object

In [304]:
df.info() # to get information about data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    2 non-null      int64
 1   col2    2 non-null      int64
 2   col3    2 non-null      int64
dtypes: int64(3)
memory usage: 180.0 bytes


In [306]:
df.values

array([[1, 3, 5],
       [2, 4, 6]], dtype=int64)

In [307]:
df.axes

[RangeIndex(start=0, stop=2, step=1),
 Index(['col1', 'col2', 'col3'], dtype='object')]

In [309]:
df.ndim

2

In [310]:
df.size

6

In [348]:
#to access specific column  in df
type(df['w'])

pandas.core.series.Series

In [349]:
df[['w','x','y']]

w         x         y
A -0.082347 -0.751475  0.623973
B  0.436654  0.179722  0.193585
C -0.006839 -1.989425  0.534744
D -0.859714  1.503477  1.560717
E  0.743590  1.038990 -0.523050

In [350]:
#to access multiple columns
df[['w', 'x', 'y']]

w         x         y
A -0.082347 -0.751475  0.623973
B  0.436654  0.179722  0.193585
C -0.006839 -1.989425  0.534744
D -0.859714  1.503477  1.560717
E  0.743590  1.038990 -0.523050

In [352]:
#to create new column
df['new'] = df['w']+df['y']
df

w         x         y         z       new
A -0.082347 -0.751475  0.623973 -0.185253  0.541626
B  0.436654  0.179722  0.193585  2.167517  0.630240
C -0.006839 -1.989425  0.534744 -0.840111  0.527905
D -0.859714  1.503477  1.560717 -0.320598  0.701003
E  0.743590  1.038990 -0.523050 -1.369887  0.220540

In [353]:
df.drop('new', axis=1)

w         x         y         z
A -0.082347 -0.751475  0.623973 -0.185253
B  0.436654  0.179722  0.193585  2.167517
C -0.006839 -1.989425  0.534744 -0.840111
D -0.859714  1.503477  1.560717 -0.320598
E  0.743590  1.038990 -0.523050 -1.369887

In [356]:
df.drop('new', axis=1, inplace=True)


KeyError: "['new'] not found in axis"

In [357]:
df

w         x         y         z
A -0.082347 -0.751475  0.623973 -0.185253
B  0.436654  0.179722  0.193585  2.167517
C -0.006839 -1.989425  0.534744 -0.840111
D -0.859714  1.503477  1.560717 -0.320598
E  0.743590  1.038990 -0.523050 -1.369887