In [1]:
import numpy as np
import pandas as pd
# 1.) Add another row to this array
# row to be added = [12,23,45] 
# ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

row_to_be_added = [12, 23, 45]
ini_array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
ini_array = np.append(ini_array, [row_to_be_added], axis=0)
print(ini_array)



[[ 1  2  3]
 [45  4  7]
 [ 9  6 10]
 [12 23 45]]


In [2]:
# 2.) Find the frequency of all elements in the series
# se = pd.Series([1,1,1,2,2,2,2,3,3,3,4,4,5])

se = pd.Series([1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 4, 4, 5])
frequency = se.value_counts()
print(frequency)


2    4
1    3
3    3
4    2
5    1
Name: count, dtype: int64


In [3]:
# 3.) Reshape the series ser into a dataframe
# ser = pd.Series(np.random.randint(1, 10, 35))

ser = pd.Series(np.random.randint(1, 10, 35))
df = pd.DataFrame(ser.values.reshape(7, 5))
print(df)


   0  1  2  3  4
0  2  3  3  5  5
1  1  1  4  7  8
2  8  8  2  5  7
3  7  6  4  1  2
4  8  8  6  9  8
5  8  7  8  8  7
6  4  3  7  6  3


In [4]:
# 4.) Find the positions of numbers that are multiples of 3 from ser
# ser = pd.Series(np.random.randint(1, 10, 10))

ser = pd.Series(np.random.randint(1, 10, 10))
positions = ser[ser % 3 == 0].index
print("4",positions)


4 Index([1, 3, 5], dtype='int64')


In [5]:
# 5.) Join the two series
# ser1 = pd.Series(range(5))
# ser2 = pd.Series(list('abcde'))

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
joined_series = ser1.append(ser2)
print(joined_series)


AttributeError: 'Series' object has no attribute 'append'

In [6]:
# 6.) Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.
# Sample Python dictionary data and list labels
# exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
# 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
# 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
# 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
# labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

exam_data = {
'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(exam_data, index=labels)
selected_columns = df[['name', 'score']]
print(selected_columns)

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0


In [9]:
# 5.) Join the two series
# ser1 = pd.Series(range(5))
# ser2 = pd.Series(list('abcde'))

ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
joined_Series = ser1.append(ser2)
print(joined_Series)


AttributeError: 'Series' object has no attribute 'append'